name: Tests

on: [push, pull_request]

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.1.0
        with: 
          cmd: yarn install

      - name: Run tests
        uses: Borales/actions-yarn@v2.1.0
        with: 
          cmd: yarn test

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == 10
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./js/coverage/lcov.info"
